### ISSUE TITLE
NullPointerException on spigot 1.8 R0.1 server

### ISSUE THREAD

**Issue by Jonas-Bartkowski** [Cybermaxke/Merchants#15]
So I tried using your plugin with my spigot 1.8 R0.1 server and it always throws me a NullPointerException when I do Merchants.get(). Is this because there is no support for 1.8 or because I didn't implement it correctly? 

I get the same Exception whether I use merchants-api-1.5.1 or merchants-spigot-mc1.8.4-1.5.1.

**Comment by Bl4ckSkull666** [comment]
Can u post the NPE and the code +/- 10 lines?

**Comment by Jonas-Bartkowski** [comment]
Thank you for responding. 
Code (Class BedwarsCommandExecutor, starts with line 58, ends with line 79):
https://hastebin.com/rihovovohe.cs

NPE:
[14:33:43] [Server thread/WARN]: java.lang.NullPointerException
[14:33:43] [Server thread/WARN]: at com.chaoscrasher.bedwars.main.BedwarsAdminCommandExcecutor.onCommand(BedwarsAdminCommandExcecutor.java:64)
[14:33:43] [Server thread/WARN]: at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[14:33:43] [Server thread/WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[14:33:43] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_8_R1.CraftServer.dispatchCommand(CraftServer.java:645)
[14:33:43] [Server thread/WARN]: at net.minecraft.server.v1_8_R1.PlayerConnection.handleCommand(PlayerConnection.java:1115)
[14:33:43] [Server thread/WARN]: at net.minecraft.server.v1_8_R1.PlayerConnection.a(PlayerConnection.java:950)
[14:33:43] [Server thread/WARN]: at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:26)
[14:33:43] [Server thread/WARN]: at net.minecraft.server.v1_8_R1.PacketPlayInChat.a(PacketPlayInChat.java:53)
[14:33:43] [Server thread/WARN]: at net.minecraft.server.v1_8_R1.PacketHandleTask.run(SourceFile:13)
[14:33:43] [Server thread/WARN]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[14:33:43] [Server thread/WARN]: at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[14:33:43] [Server thread/WARN]: at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:683)
[14:33:43] [Server thread/WARN]: at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316)
[14:33:43] [Server thread/WARN]: at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623)
[14:33:43] [Server thread/WARN]: at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526)
[14:33:43] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)

It basically doesn't get a non-null MerchantAPI reference.

**Comment by elgbar** [comment]
I looked at some of my old code and it included this:
```
// create merchant
final MerchantAPI api = Merchants.get();
final Merchant merchant;
try {
        Main.log("Raw Merchant name: " + trader.getDisplayName());
        merchant = api.newMerchant(trader.getDisplayName(), true);

    } catch (final NullPointerException e) {
        throw new NullPointerException("Could not open merchant as the api is not enabled.");
}
```

So your problem might be that the api is not enabled...
Do you have a copy of the MerchantAPI in your plugin folder?

**Comment by Jonas-Bartkowski** [comment]
I didn't put it into my plugin folder per se, rather into a custom lib folder. My manifest.mf then points to that location (if I don't do that I get NoClasDefFoundError, not NPE). I tried including it into the plugin folder as well, but that doesn't change the error in any way.

Thank you for responding so quickly, that really is nice of you.

**Comment by elgbar** [comment]
Hmm weir, first of all why don't you just shade it into your jar? And secondly you need it in the plugins folder as it is a plugin. Look at [my code](https://github.com/kh498/TraderSk/blob/master/src/main/java/com/kh498/main/Main.java#L88) to see how I did it.

**Comment by Jonas-Bartkowski** [comment]
I did put it into my plugin folder now, but I get the same error :| 
I didn't shard it into my jar because the plugin doesn't work then (NoClassDefFoundError because eclipse doesn't connect the jars properly.) I wish I could do it like that but Eclipse is not doing it correctly on my machine for some reason.

**Comment by Bl4ckSkull666** [comment]
Do u have initialized MerchantAPI?

Change your code to this one https://hastebin.com/enibaritus.cs

**Comment by Jonas-Bartkowski** [comment]
That Class is not exposed to me if I just have merchants-api-1.5.1.jar in my project. If I have merchants-spigot-mc1.8.4-1.5.1.jar in my project I don't get NPE anymore but now

Caused by: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R3/IMerchant
at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_144]

Thank you for being so patient with me.

**Comment by Bl4ckSkull666** [comment]
Dont use the jar files. Add the source folder v18r3 and api to your code. It's the easiest and best way.

U need this both folders
- MerchantsAPI/api/src/main/java/me/cybermaxke/merchants/api/
- MerchantsAPI/spigot/v18r3/src/main/java/me/cybermaxke/merchants/v18r3/

Download the full source from GitHub and copsy this both folders in your project.
